Add sys-process/procps overlay
Similar to sys-process/psmisc, sys-process/procps fails to build with
errors like:
> ld: pwdx.o: in function `xmalloc':
> pwdx.c:(.text+0xf8): undefined reference to `rpl_malloc'

This change fixes the problem by telling autoconf to just use the malloc
provided instead of probing for its compatibility.