Add sys-process/psmisc overlay
This change adds an overlay for sys-process/psmisc which resolves
problems of the form:
  > ld: pstree.c:(.text+0x1248): undefined reference to `rpl_malloc'

by telling autoconf to just use the malloc provided instead of probing
for its compatibility.